const { line } = require('../helpers')

const prefix = 'foospidy/payloads.git@d11b18ceb09db78728a79765a9ccdd2939be9d6c'

const dicts = {
    'foospidy': {
        ...line({ prefix, suffix: "other/codeinjection/struts.txt", stats: "24 lines, 14462 bytes" }),
        ...line({ prefix, suffix: "other/codeinjection/fede.txt", stats: "5 lines, 2225 bytes" }),
        ...line({ prefix, suffix: "other/traversal/dotdotpwn.txt", stats: "21144 lines, 1872006 bytes" }),
        ...line({ prefix, suffix: "other/xss/secgeek.txt", stats: "9 lines, 215 bytes" }),
        ...line({ prefix, suffix: "other/xss/jsf__k.txt", stats: "1 lines, 46 bytes" }),
        ...line({ prefix, suffix: "other/xss/soaj1664ashar.txt", stats: "99 lines, 7790 bytes" }),
        ...line({ prefix, suffix: "other/xss/ismailtasdelen.txt", stats: "2674 lines, 183159 bytes" }),
        ...line({ prefix, suffix: "other/xss/smeegesec.com.txt", stats: "298 lines, 17793 bytes" }),
        ...line({ prefix, suffix: "other/xss/0xsobky.txt", stats: "1 lines, 145 bytes" }),
        ...line({ prefix, suffix: "other/xss/rafaybaloch.txt", stats: "174 lines, 13521 bytes" }),
        ...line({ prefix, suffix: "other/xss/reddit_xss_get.txt", stats: "572 lines, 60997 bytes" }),
        ...line({ prefix, suffix: "other/xss/XssPayloads.txt", stats: "21 lines, 1765 bytes" }),
        ...line({ prefix, suffix: "other/xss/bhandarkar.txt", stats: "715 lines, 50543 bytes" }),
        ...line({ prefix, suffix: "other/xss/787373.txt", stats: "232 lines, 25588 bytes" }),
        ...line({ prefix, suffix: "other/xss/xssdb.txt", stats: "217 lines, 16413 bytes" }),
        ...line({ prefix, suffix: "other/xss/billsempf.txt", stats: "665 lines, 45997 bytes" }),
        ...line({ prefix, suffix: "other/xss/kirankarnad.txt", stats: "98 lines, 7704 bytes" }),
        ...line({ prefix, suffix: "other/xss/packetstorm.txt", stats: "389 lines, 25898 bytes" }),
        ...line({ prefix, suffix: "other/xss/alternume0.txt", stats: "0 lines, 79 bytes" }),
        ...line({ prefix, suffix: "other/xss/d3adend.org.txt", stats: "91 lines, 8148 bytes" }),
        ...line({ prefix, suffix: "other/commandinjection/ismailtasdelen-windows.txt", stats: "447 lines, 20288 bytes" }),
        ...line({ prefix, suffix: "other/commandinjection/ismailtasdelen-unix.txt", stats: "69 lines, 982 bytes" }),
        ...line({ prefix, suffix: "other/sqli/c0rni3sm.txt", stats: "4 lines, 152 bytes" }),
        ...line({ prefix, suffix: "other/sqli/camoufl4g3.txt", stats: "77 lines, 1180 bytes" }),
        ...line({ prefix, suffix: "other/sqli/libinjection-bypasses.txt", stats: "474 lines, 32470 bytes" }),
        ...line({ prefix, suffix: "other/sqli/d0znpp.txt", stats: "9 lines, 316 bytes" }),
        ...line({ prefix, suffix: "other/sqli/sqlifuzzer.txt", stats: "86 lines, 2207 bytes" }),
        ...line({ prefix, suffix: "other/sqli/jstnkndy.txt", stats: "0 lines, 189 bytes" }),
        ...line({ prefix, suffix: "other/sqli/harisec.txt", stats: "2 lines, 130 bytes" }),
        ...line({ prefix, suffix: "owasp/fuzzing_code_database/http/verbs.txt", stats: "30 lines, 241 bytes" }),
        ...line({ prefix, suffix: "owasp/fuzzing_code_database/ssi/ssi.txt", stats: "3 lines, 221 bytes" }),
        ...line({ prefix, suffix: "owasp/fuzzing_code_database/format_string.txt", stats: "27 lines, 629 bytes" }),
        ...line({ prefix, suffix: "owasp/fuzzing_code_database/directory_traversal/deep_traversal.txt", stats: "878 lines, 68683 bytes" }),
        ...line({ prefix, suffix: "owasp/fuzzing_code_database/directory_traversal/directory_traversal.txt", stats: "131 lines, 8262 bytes" }),
        ...line({ prefix, suffix: "owasp/fuzzing_code_database/xss/xml.txt", stats: "14 lines, 1546 bytes" }),
        ...line({ prefix, suffix: "owasp/fuzzing_code_database/xss/discovery.txt", stats: "1 lines, 251 bytes" }),
        ...line({ prefix, suffix: "owasp/fuzzing_code_database/xss/common.txt", stats: "5 lines, 336 bytes" }),
        ...line({ prefix, suffix: "owasp/fuzzing_code_database/xss/full.txt", stats: "166 lines, 11095 bytes" }),
        ...line({ prefix, suffix: "owasp/fuzzing_code_database/dirs/coldfusion_common.txt", stats: "64 lines, 2031 bytes" }),
        ...line({ prefix, suffix: "owasp/fuzzing_code_database/dirs/lotus_common.txt", stats: "110 lines, 1465 bytes" }),
        ...line({ prefix, suffix: "owasp/fuzzing_code_database/dirs/windows_cgi_common.txt", stats: "75 lines, 1988 bytes" }),
        ...line({ prefix, suffix: "owasp/fuzzing_code_database/dirs/cgi_common.txt", stats: "562 lines, 15404 bytes" }),
        ...line({ prefix, suffix: "owasp/fuzzing_code_database/dirs/sap_common.txt", stats: "154 lines, 4425 bytes" }),
        ...line({ prefix, suffix: "owasp/fuzzing_code_database/dirs/microsoft_common.txt", stats: "78 lines, 1560 bytes" }),
        ...line({ prefix, suffix: "owasp/fuzzing_code_database/dirs/adobe_xml_files.txt", stats: "15 lines, 427 bytes" }),
        ...line({ prefix, suffix: "owasp/fuzzing_code_database/sqli/sqli.txt", stats: "141 lines, 2118 bytes" }),
        ...line({ prefix, suffix: "owasp/dirbuster/directory-list-2.3-big.txt", stats: "1273833 lines, 14802893 bytes" }),
        ...line({ prefix, suffix: "owasp/dirbuster/directory-list-2.3-small.txt", stats: "87664 lines, 725439 bytes" }),
        ...line({ prefix, suffix: "owasp/dirbuster/directory-list-lowercase-2.3-medium.txt", stats: "207643 lines, 1849676 bytes" }),
        ...line({ prefix, suffix: "owasp/dirbuster/apache-user-enum-2.0.txt", stats: "10355 lines, 90418 bytes" }),
        ...line({ prefix, suffix: "owasp/dirbuster/apache-user-enum-1.0.txt", stats: "8930 lines, 71638 bytes" }),
        ...line({ prefix, suffix: "owasp/dirbuster/directory-list-lowercase-2.3-big.txt", stats: "1185254 lines, 13192483 bytes" }),
        ...line({ prefix, suffix: "owasp/dirbuster/directory-list-1.0.txt", stats: "141708 lines, 1802668 bytes" }),
        ...line({ prefix, suffix: "owasp/dirbuster/directory-list-lowercase-2.3-small.txt", stats: "81643 lines, 676768 bytes" }),
        ...line({ prefix, suffix: "owasp/dirbuster/directory-list-2.3-medium.txt", stats: "220560 lines, 1980043 bytes" }),
        ...line({ prefix, suffix: "owasp/jbrofuzz/xss.txt", stats: "226 lines, 18643 bytes" }),
        ...line({ prefix, suffix: "owasp/jbrofuzz/ldap.txt", stats: "13 lines, 108 bytes" }),
        ...line({ prefix, suffix: "owasp/jbrofuzz/sqli.txt", stats: "166 lines, 11654 bytes" }),
        ...line({ prefix, suffix: "owasp/jbrofuzz/windows_variables.txt", stats: "25 lines, 290 bytes" }),
        ...line({ prefix, suffix: "owasp/jbrofuzz/iis_cgi.txt", stats: "641 lines, 16965 bytes" }),
        ...line({ prefix, suffix: "owasp/jbrofuzz/xpath.txt", stats: "9 lines, 113 bytes" }),
        ...line({ prefix, suffix: "owasp/jbrofuzz/http_verbs.txt", stats: "15 lines, 93 bytes" }),
    }
}

exports.dicts = dicts
